import { Injectable } from '@nestjs/common'

@Injectable()
export class AppService {
  root(): string {
    return `
      Hello World!
      + User
        - register:     /users/signup?username=...&password=...&cpassword=...&fullname=...
        - login:        /users/signin?username=...&password=...
        - users list:   /users/list
      + Children
        - children list:  /children/list
        - create:         /children/create?name=...&dob=...&userId=...
        - update:         /children/update?id=...&name=...
        - delete:         /children/delete?id=...
      + Vaccin
        - vaccins list:   /vaccin/list
        - create:         /vaccin/create?name=...&description=...&availableAge=...
        - update:         /vaccin/update?id=...&name=...&description=...&availableAge=...
        - delete:         /vaccin/delete?id=...
      + Inject address
        - i.a list:       /ia/list
        - create:         /ia/create?name=...&address=...
        - update:         /ia/update?id=...&name=...&address=...
        - delete:         /ia/delete?id=...
      + Inject record
        - i.r list:       /ir/list
        - create:         /ir/create?childrenId=...&vaccinId=...&injectAt=...
        - update:         /ir/update?id=...&vaccinId=...&injectAt=...
        - delete:         /ir/delete?id=...
      `
  }
}
